### PR TITLE
[Not working yet, keep open] Docker file and update instructions for that

### PR DESCRIPTION
**Pull request by pablodz**
Not merge update.rm 
Just add docker steps in other sections.

### CODE REVIEW

**Comment by tom-doerr** [comment]
I saw that you added the note "not completely implemented" in the readme. Are there issues when executing parts of the code?

**Comment by ZurMaD** [comment]
> I saw that you added the note "not completely implemented" in the readme. Are there issues when executing parts of the code?

Yes @tom-doerr I find some errors, not building the docker, running the script to test but I have not enough time to test and fix it. 
I'll check this week to build correctly the Docker for test & train.

**Comment by tom-doerr** [comment]
I fixed a bug in my repo (https://github.com/tom-doerr/TecoGAN).
In case you still have issues you might want to try out the new version.

**Comment by ZurMaD** [comment]
> I fixed a bug in my repo (https://github.com/tom-doerr/TecoGAN).
> In case you still have issues you might want to try out the new version.

Thanks, I will check these days

**Pull request closed without merging**
